pub use crate::prelude::*;

/// The contact's detected language. Empty string when no language has been detected or set.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AudiencesContactLanguage {
    Empty,
    En,
    Ar,
    Af,
    Be,
    Bg,
    Ca,
    Zh,
    ZhCn,
    Hr,
    Cs,
    Da,
    Nl,
    Et,
    Fa,
    Fi,
    Fr,
    FrCa,
    De,
    El,
    He,
    Hi,
    Hu,
    Is,
    Id,
    Ga,
    It,
    Ja,
    Km,
    Ko,
    Lv,
    Lt,
    Mt,
    Ms,
    Mk,
    No,
    Pl,
    Pt,
    PtPt,
    Ro,
    Ru,
    Sr,
    Sk,
    Sl,
    Es,
    EsEs,
    Sw,
    Sv,
    Ta,
    Th,
    Tr,
    Uk,
    Vi,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for AudiencesContactLanguage {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Empty => serializer.serialize_str(""),
            Self::En => serializer.serialize_str("en"),
            Self::Ar => serializer.serialize_str("ar"),
            Self::Af => serializer.serialize_str("af"),
            Self::Be => serializer.serialize_str("be"),
            Self::Bg => serializer.serialize_str("bg"),
            Self::Ca => serializer.serialize_str("ca"),
            Self::Zh => serializer.serialize_str("zh"),
            Self::ZhCn => serializer.serialize_str("zh_CN"),
            Self::Hr => serializer.serialize_str("hr"),
            Self::Cs => serializer.serialize_str("cs"),
            Self::Da => serializer.serialize_str("da"),
            Self::Nl => serializer.serialize_str("nl"),
            Self::Et => serializer.serialize_str("et"),
            Self::Fa => serializer.serialize_str("fa"),
            Self::Fi => serializer.serialize_str("fi"),
            Self::Fr => serializer.serialize_str("fr"),
            Self::FrCa => serializer.serialize_str("fr_CA"),
            Self::De => serializer.serialize_str("de"),
            Self::El => serializer.serialize_str("el"),
            Self::He => serializer.serialize_str("he"),
            Self::Hi => serializer.serialize_str("hi"),
            Self::Hu => serializer.serialize_str("hu"),
            Self::Is => serializer.serialize_str("is"),
            Self::Id => serializer.serialize_str("id"),
            Self::Ga => serializer.serialize_str("ga"),
            Self::It => serializer.serialize_str("it"),
            Self::Ja => serializer.serialize_str("ja"),
            Self::Km => serializer.serialize_str("km"),
            Self::Ko => serializer.serialize_str("ko"),
            Self::Lv => serializer.serialize_str("lv"),
            Self::Lt => serializer.serialize_str("lt"),
            Self::Mt => serializer.serialize_str("mt"),
            Self::Ms => serializer.serialize_str("ms"),
            Self::Mk => serializer.serialize_str("mk"),
            Self::No => serializer.serialize_str("no"),
            Self::Pl => serializer.serialize_str("pl"),
            Self::Pt => serializer.serialize_str("pt"),
            Self::PtPt => serializer.serialize_str("pt_PT"),
            Self::Ro => serializer.serialize_str("ro"),
            Self::Ru => serializer.serialize_str("ru"),
            Self::Sr => serializer.serialize_str("sr"),
            Self::Sk => serializer.serialize_str("sk"),
            Self::Sl => serializer.serialize_str("sl"),
            Self::Es => serializer.serialize_str("es"),
            Self::EsEs => serializer.serialize_str("es_ES"),
            Self::Sw => serializer.serialize_str("sw"),
            Self::Sv => serializer.serialize_str("sv"),
            Self::Ta => serializer.serialize_str("ta"),
            Self::Th => serializer.serialize_str("th"),
            Self::Tr => serializer.serialize_str("tr"),
            Self::Uk => serializer.serialize_str("uk"),
            Self::Vi => serializer.serialize_str("vi"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for AudiencesContactLanguage {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "" => Ok(Self::Empty),
            "en" => Ok(Self::En),
            "ar" => Ok(Self::Ar),
            "af" => Ok(Self::Af),
            "be" => Ok(Self::Be),
            "bg" => Ok(Self::Bg),
            "ca" => Ok(Self::Ca),
            "zh" => Ok(Self::Zh),
            "zh_CN" => Ok(Self::ZhCn),
            "hr" => Ok(Self::Hr),
            "cs" => Ok(Self::Cs),
            "da" => Ok(Self::Da),
            "nl" => Ok(Self::Nl),
            "et" => Ok(Self::Et),
            "fa" => Ok(Self::Fa),
            "fi" => Ok(Self::Fi),
            "fr" => Ok(Self::Fr),
            "fr_CA" => Ok(Self::FrCa),
            "de" => Ok(Self::De),
            "el" => Ok(Self::El),
            "he" => Ok(Self::He),
            "hi" => Ok(Self::Hi),
            "hu" => Ok(Self::Hu),
            "is" => Ok(Self::Is),
            "id" => Ok(Self::Id),
            "ga" => Ok(Self::Ga),
            "it" => Ok(Self::It),
            "ja" => Ok(Self::Ja),
            "km" => Ok(Self::Km),
            "ko" => Ok(Self::Ko),
            "lv" => Ok(Self::Lv),
            "lt" => Ok(Self::Lt),
            "mt" => Ok(Self::Mt),
            "ms" => Ok(Self::Ms),
            "mk" => Ok(Self::Mk),
            "no" => Ok(Self::No),
            "pl" => Ok(Self::Pl),
            "pt" => Ok(Self::Pt),
            "pt_PT" => Ok(Self::PtPt),
            "ro" => Ok(Self::Ro),
            "ru" => Ok(Self::Ru),
            "sr" => Ok(Self::Sr),
            "sk" => Ok(Self::Sk),
            "sl" => Ok(Self::Sl),
            "es" => Ok(Self::Es),
            "es_ES" => Ok(Self::EsEs),
            "sw" => Ok(Self::Sw),
            "sv" => Ok(Self::Sv),
            "ta" => Ok(Self::Ta),
            "th" => Ok(Self::Th),
            "tr" => Ok(Self::Tr),
            "uk" => Ok(Self::Uk),
            "vi" => Ok(Self::Vi),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for AudiencesContactLanguage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => write!(f, ""),
            Self::En => write!(f, "en"),
            Self::Ar => write!(f, "ar"),
            Self::Af => write!(f, "af"),
            Self::Be => write!(f, "be"),
            Self::Bg => write!(f, "bg"),
            Self::Ca => write!(f, "ca"),
            Self::Zh => write!(f, "zh"),
            Self::ZhCn => write!(f, "zh_CN"),
            Self::Hr => write!(f, "hr"),
            Self::Cs => write!(f, "cs"),
            Self::Da => write!(f, "da"),
            Self::Nl => write!(f, "nl"),
            Self::Et => write!(f, "et"),
            Self::Fa => write!(f, "fa"),
            Self::Fi => write!(f, "fi"),
            Self::Fr => write!(f, "fr"),
            Self::FrCa => write!(f, "fr_CA"),
            Self::De => write!(f, "de"),
            Self::El => write!(f, "el"),
            Self::He => write!(f, "he"),
            Self::Hi => write!(f, "hi"),
            Self::Hu => write!(f, "hu"),
            Self::Is => write!(f, "is"),
            Self::Id => write!(f, "id"),
            Self::Ga => write!(f, "ga"),
            Self::It => write!(f, "it"),
            Self::Ja => write!(f, "ja"),
            Self::Km => write!(f, "km"),
            Self::Ko => write!(f, "ko"),
            Self::Lv => write!(f, "lv"),
            Self::Lt => write!(f, "lt"),
            Self::Mt => write!(f, "mt"),
            Self::Ms => write!(f, "ms"),
            Self::Mk => write!(f, "mk"),
            Self::No => write!(f, "no"),
            Self::Pl => write!(f, "pl"),
            Self::Pt => write!(f, "pt"),
            Self::PtPt => write!(f, "pt_PT"),
            Self::Ro => write!(f, "ro"),
            Self::Ru => write!(f, "ru"),
            Self::Sr => write!(f, "sr"),
            Self::Sk => write!(f, "sk"),
            Self::Sl => write!(f, "sl"),
            Self::Es => write!(f, "es"),
            Self::EsEs => write!(f, "es_ES"),
            Self::Sw => write!(f, "sw"),
            Self::Sv => write!(f, "sv"),
            Self::Ta => write!(f, "ta"),
            Self::Th => write!(f, "th"),
            Self::Tr => write!(f, "tr"),
            Self::Uk => write!(f, "uk"),
            Self::Vi => write!(f, "vi"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
